name: Build

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.21"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
      - name: Build ARM64
        run: GOOS=linux GOARCH=arm64 go build -o launch-agent-linux-arm64 .
      - name: Build ARM
        run: GOOS=linux GOARCH=arm go build -o launch-agent-linux-arm .
      - name: Build AMD64
        run: GOOS=linux GOARCH=amd64 go build -o launch-agent-linux-amd64 .
      - name: Build AMD
        run: GOOS=linux GOARCH=386 go build -o launch-agent-linux-amd .
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./launch-agent-linux-arm64
          asset_name: launch-agent-linux-arm64
          asset_content_type: application/octet-stream
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./launch-agent-linux-arm
          asset_name: launch-agent-linux-arm
          asset_content_type: application/octet-stream
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./launch-agent-linux-amd64
          asset_name: launch-agent-linux-amd64
          asset_content_type: application/octet-stream
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./launch-agent-linux-amd
          asset_name: launch-agent-linux-amd
          asset_content_type: application/octet-stream